import styles from "../../styles/Home.module.css";
import React, { FC } from "react";
import Head from "next/head";
import { Footer } from "../organisms/footer";
import { PageSubtitle } from "../atoms/page-subtitle";
import { PageTitle } from "../atoms/page-title";

export const Layout: FC = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <PageTitle />
        <PageSubtitle />
        {children}
      </main>

      <Footer />
    </div>
  );
};
